module.exports = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  COMPLETE_TASK: "COMPLETE_TASK",
  DELETE_TASK: "DELETE_TASK",
  DATE_TASK : "DATE_TASK",

  ADD_EXPENSE: "ADD_EXPENSE",
  UPDATE_EXPENSE: "UPDATE_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",

  CREATE_DAILYINFO: "CREATE_DAILYINFO",
  DATE_DAILYINFO: "DATE_DAILYINFO",
  UPDATE_DAILYINFO: "UPDATE_DAILYINFO",
  DELETE_DAILYINFO: "DELETE_DAILYINFO",

  
};
