// const transporter = require("../config/mailConfig");

// const sendDelayTaskEmail = async (email, title, scheduledTime) => {
//   const mailOptions = {
//     from: process.env.EMAIL_USER,
//     to: email,
//     subject: "⏰ Todo Reminder",
//     html: `
//       <h2>Hello!</h2>

//       <p>Your scheduled task is still pending.</p>

//       <table border="1" cellpadding="8" cellspacing="0">
//         <tr>
//           <td><b>Task</b></td>
//           <td>${title}</td>
//         </tr>

//         <tr>
//           <td><b>Scheduled Time</b></td>
//           <td>${scheduledTime}</td>
//         </tr>
//       </table>

//       <br>

//       <p>
//         Please open the application and either:
//       </p>

//       <ul>
//         <li>✅ Complete the task</li>
//         <li>📝 Add a delay reason if you couldn't complete it</li>
//       </ul>

//       <br>

//       <b>Daily Planner</b>
//     `,
//   };
//   return transporter.sendMail(mailOptions);
// };

// module.exports = {
//   sendDelayTaskEmail,
// };
const transporter = require("../config/mailConfig");

console.log("Transporter =", transporter);

const sendDelayTaskEmail = async (email, userName, todo) => {
  const taskUrl = `${process.env.FRONTEND_URL}/dashboard`;
  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: email,
    subject: `Task Reminder: ${todo.title}`,
    html: `
      <div style="font-family: Arial, Helvetica, sans-serif; max-width:700px; margin:auto; border:1px solid #e5e5e5; border-radius:8px; overflow:hidden;">
        
        <div style="background:#1976d2; color:#ffffff; padding:20px;">
          <h2 style="margin:0;">Daily Tracker</h2>
          <p style="margin:6px 0 0;">Task Reminder Notification</p> 
          <a href="${taskUrl}">
  Open Daily Tracker
</a>
        </div>

        <div style="padding:25px; color:#333;">

          <p>Dear <strong>${userName},</strong></p>

          <p>
            This is a reminder that the following task is still marked as
            <strong>Pending</strong> and has exceeded its scheduled completion time.
          </p>

          <table style="width:100%; border-collapse:collapse; margin-top:20px;">
            <tr>
              <td style="padding:10px; border:1px solid #ddd; background:#f7f7f7;"><strong>Task Title</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${todo.title}</td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd; background:#f7f7f7;"><strong>Description</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${todo.description || "-"}</td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd; background:#f7f7f7;"><strong>Date</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">
                ${new Date(todo.date).toLocaleDateString()}
              </td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd; background:#f7f7f7;"><strong>Scheduled Time</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${todo.scheduledTime}</td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd; background:#f7f7f7;"><strong>Status</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${todo.status}</td>
            </tr>

            <tr>
              <td style="padding:10px; border:1px solid #ddd; background:#f7f7f7;"><strong>Task Type</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${todo.taskType}</td>
            </tr>

            ${
              todo.taskType === "MEASURABLE"
                ? `
            <tr>
              <td style="padding:10px; border:1px solid #ddd; background:#f7f7f7;"><strong>Target</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">
                ${todo.targetvalue} ${todo.unit}
              </td>
            </tr>`
                : `
            <tr>
              <td style="padding:10px; border:1px solid #ddd; background:#f7f7f7;"><strong>Priority</strong></td>
              <td style="padding:10px; border:1px solid #ddd;">${todo.priority || "-"}</td>
            </tr>`
            }
          </table>

          <div style="margin-top:25px;">
            <p>
              Please log in to the <strong>Daily Tracker</strong> application and complete one of the following actions:
            </p>

            <ul>
              <li>Mark the task as <strong>Completed</strong>, or</li>
              <li>Provide a valid <strong>Delay Reason</strong> if the task could not be completed.</li>
            </ul>
          </div>

          <p style="margin-top:25px;">
            This is an automated reminder generated by the Daily Tracker system.
            No reply is required.
          </p>

          <p>
            Regards,<br>
            <strong>Daily Tracker Team</strong>
          </p>

        </div>

        <div style="background:#f5f5f5; padding:15px; text-align:center; font-size:12px; color:#666;">
          Reminder Generated on: ${new Date().toLocaleString()}
        </div>

      </div>
    `,
  };

  return transporter.sendMail(mailOptions);
};

module.exports = {
  sendDelayTaskEmail,
};
